apiVersion: v1
kind: Service
metadata:
  name: restaurant-db
  namespace: fooddelivery
spec:
  selector:
    app: restaurant-db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
