apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-db
  namespace: fooddelivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-db
  template:
    metadata:
      labels:
        app: restaurant-db
    spec:
      containers:
        - name: mongo
          image: mongo:4.4
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: restaurant-db-data
              mountPath: /data/db
      volumes:
        - name: restaurant-db-data
          emptyDir: {}
