apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: fooddelivery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      initContainers:
        - name: wait-for-user-db
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nc -z user-db 27017; do echo waiting for user-db; sleep 2; done;",
            ]
      containers:
        - name: user-service
          image: nsvpavan/backend-user-service:latest
          ports:
            - containerPort: 3001
          env:
            - name: MONGODB_URI
              value: "mongodb://user-db:27017/users"
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 15
            periodSeconds: 20
